"""
Django settings for django_12 project.

Generated by 'django-admin startproject' using Django 2.1.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

# python与系统交互的操作模块
import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
# 制定项目绝对路径
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# 加密盐，保证项目的唯一性
SECRET_KEY = '*nnd+#1cnk-l5@%mc)imukg5v+0xk71+n#t!k6n_ajcozh%gud'

# SECURITY WARNING: don't run with debug turned on in production!
# 错误提示  True会提示错误位置  False在上线中看
DEBUG = True

# 指定访问IP *：所有ip都能访问
ALLOWED_HOSTS = []

# Application definition
# 注册应用
# admin站点；认证系统，识别密码，身份；内容类型的框架；session会话框架；消息传递框架；用于管理静态文件的框架
# installed_apps
INSTALLED_APPS = [
	'django.contrib.admin',
	'django.contrib.auth',
	'django.contrib.contenttypes',
	'django.contrib.sessions',
	'django.contrib.messages',
	'django.contrib.staticfiles',
	'common',
	'two',
	'three',
	'four',
	'five',
	'six',
	'seven',
	'eight',
	'nine',
	'ten',
	'eleven',
	'twelve',
]
# 中间件
MIDDLEWARE = [
	'django.middleware.security.SecurityMiddleware',
	'django.contrib.sessions.middleware.SessionMiddleware',
	'django.middleware.common.CommonMiddleware',
	'django.middleware.csrf.CsrfViewMiddleware',
	'django.contrib.auth.middleware.AuthenticationMiddleware',
	'django.contrib.messages.middleware.MessageMiddleware',
	'django.middleware.clickjacking.XFrameOptionsMiddleware',
	'twelve.mymiddleware.MyException',
	'twelve.mymiddleware.UserMiddleware',
]
# 总路由
ROOT_URLCONF = 'django_12.urls'
# 模板
TEMPLATES = [
	{
		'BACKEND': 'django.template.backends.django.DjangoTemplates',
		# 将templates目录路径添加到配置文件中，进行注册
		'DIRS': [os.path.join(BASE_DIR, 'templates')],
		'APP_DIRS': True,
		'OPTIONS': {
			'context_processors': [
				'django.template.context_processors.debug',
				'django.template.context_processors.request',
				'django.contrib.auth.context_processors.auth',
				'django.contrib.messages.context_processors.messages',
				'twelve.mycontextprocessor.my_user',
			],
		},
	},
]

WSGI_APPLICATION = 'django_12.wsgi.application'

# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases
# 数据库的配置
DATABASES = {
	'default': {
		# 'ENGINE': 'django.db.backends.sqlite3',
		# 'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
		'ENGINE': 'django.db.backends.mysql',  # 数据引擎
		'NAME': 'django_12',  # 数据库名称
		'USER': 'admin',  # 账户
		'PASSWORD': 'qwe123',  # 密码
		'HOST': '127.0.0.1',  # mysql服务器IP地址
		'PORT': '3306'  # 端口
	}
}

# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
	{
		'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
	},
]

# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

# 设置时区
# LANGUAGE_CODE = 'en-us'	# 英文
# 语言：中文
LANGUAGE_CODE = 'zh-Hans'

# 时间设置
TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/
# 告诉项目有静态文件
STATIC_URL = '/static/'
# 指定静态文件目录路径
STATICFILES_DIRS = [
	os.path.join(BASE_DIR, "static")
]

# 文件保存路径
MEDIA_ROOT = os.path.join(BASE_DIR, 'static/media')

SESSION_SERIALIZER = 'django.contrib.sessions.serializers.PickleSerializer'