# Generated by Django 2.1 on 2021-01-14 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seven', '0002_user_city'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
