# Generated by Django 2.1 on 2021-01-20 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetails',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='city',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='sex',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
