# Generated by Django 2.1 on 2021-01-22 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nine', '0002_auto_20210120_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='credit',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.FloatField(blank=True, default=2.0),
        ),
    ]
